version: '3'
services:
  app:
    working_dir: /app
    container_name: rig_app
    command: bash -c "yarn install && yarn start"
    build:
      context: .
    volumes:
      - node_modules:/app/node-modules
      - node_modules2:/app/react-root/node_modules
    ports:
      - "3333:3000"
    tty: true
    stdin_open: true
volumes:
  node_modules:
  node_modules2:
